# Generated by Django 5.0.7 on 2024-07-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ann_title", models.CharField(default="", max_length=100)),
                ("description", models.TextField(default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("author", models.CharField(default="", max_length=200)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.ImageField(blank=True, upload_to="media/")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("debate", "Debate"),
                            ("resume", "Resume"),
                            ("review", "Review"),
                        ],
                        default="debate",
                        max_length=200,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="book_zips")),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagetitle", models.CharField(default="", max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="page_images/"
                    ),
                ),
                (
                    "txt_file",
                    models.FileField(blank=True, null=True, upload_to="book_txt"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="home.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField(default=0)),
                ("y", models.IntegerField(default=0)),
                ("w", models.IntegerField(default=0)),
                ("h", models.IntegerField(default=0)),
                ("text", models.CharField(default="", max_length=255)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="home.page",
                    ),
                ),
            ],
        ),
    ]
